# Generated by Django 4.1.5 on 2023-01-26 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('Овощи', 'ОВОЩИ'), ('Фрукты', 'ФРУКТЫ'), ('Одежда', 'ОДЕЖДА'), ('Обувь', 'ОБУВЬ')], default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
