# Generated by Django 4.1.5 on 2023-01-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categories',
            field=models.CharField(choices=[('Овощи', 'ОВОЩИ'), ('Фрукты', 'ФРУКТЫ'), ('Одежда', 'ОДЕЖДА'), ('Обувь', 'ОБУВЬ')], max_length=70, verbose_name='Категория'),
        ),
    ]
