# Generated by Django 4.1.5 on 2023-01-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_comment_created_date_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Оставьте комментарии'),
        ),
    ]
